# -*- coding: utf-8 -*-
"""display_cluster_patches.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ha2WZzjYme67LtFcx5k9_vMVd50jHvhq
"""
import matplotlib.pyplot as plt
import numpy as np

def display_cluster_patches(patches, clusters, method_name, ft_name):
    # Display 10 sample patches per cluster for visualization.
    clusters = np.array(clusters)
    unique_clusters = sorted(set(clusters))
    n_clusters = len(unique_clusters)

    n_cols = 10  # 10 samples per cluster
    n_rows = n_clusters

    plt.figure(figsize=(n_cols * 2, n_rows * 2))

    # Each row displays 10 samples of one cluster
    for row_idx, cluster_id in enumerate(unique_clusters):
        indices = np.where(clusters == cluster_id)[0]
        selected = indices[:n_cols]

        for col_idx, idx in enumerate(selected):
            plt.subplot(n_rows, n_cols, row_idx * n_cols + col_idx + 1)
            plt.imshow(patches[idx], cmap='gray')
            plt.axis('off')
            if col_idx == 0:
                plt.ylabel(f"Cluster {cluster_id}", fontsize=10)

    plt.suptitle(f"Cluster Samples - {ft_name} - {method_name}", fontsize=14)
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()