# -*- coding: utf-8 -*-
"""display_closest_and_farthest_patches_without_center_attribute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RVK6GMJNF1--8Jsh3MIFUBAjKRfJ_fmf
"""

import numpy as np
import matplotlib.pyplot as plt

def display_closest_and_farthest_patches_without_center_attribute(
    patches, features, clusters, model, method_name, ft_name, n=5
):

    # Visualize closest and farthest character patches per cluster for DBSCAN, Agglomerative, etc.
    # Use pseudo-center (mean vector) of each cluster.

    # Ensure clusters are numeric
    clusters = np.array(clusters)
    try:
        clusters = clusters.astype(int)
    except ValueError:
        # Fallback: try converting each to int individually
        clusters = np.array([int(c) for c in clusters])

    features = np.asarray(features)

    unique_clusters = sorted(c for c in set(clusters) if c != -1)
    n_clusters = len(unique_clusters)

    # Check if there are n samples in each cluster
    for cluster_id in unique_clusters:
        indices = np.where(clusters == cluster_id)[0]
        if len(indices) < n:
            continue

        # Calculate pseudo_center and sort samples based on their distances from pseudo-center
        cluster_features = features[indices]
        pseudo_center = np.mean(cluster_features, axis=0)
        dists = np.linalg.norm(cluster_features - pseudo_center, axis=1)
        sorted_indices = indices[np.argsort(dists)]

        # Select n closest and farthest
        closest = sorted_indices[:n]
        farthest = sorted_indices[-n:]

        fig, axes = plt.subplots(2, n, figsize=(n * 2, 4))
        fig.suptitle(f"Cluster {cluster_id} - {method_name} - {ft_name}", fontsize=14)

        # Show n closest images to cluster center
        for j, idx in enumerate(closest):
            axes[0, j].imshow(patches[idx], cmap='gray')
            axes[0, j].axis('off')
            axes[0, j].set_title("Close" if j == 0 else "")

        # Show n farthest images to cluster center
        for j, idx in enumerate(farthest):
            axes[1, j].imshow(patches[idx], cmap='gray')
            axes[1, j].axis('off')
            axes[1, j].set_title("Far" if j == 0 else "")

        plt.tight_layout()
        plt.show()