# -*- coding: utf-8 -*-
"""extract_features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ha2WZzjYme67LtFcx5k9_vMVd50jHvhq
"""

from skimage.feature import hog, local_binary_pattern
import cv2
import numpy as np


def extract_features(patch):
    """Extract multiple feature types from a character patch"""
    features = {}
    patch_resized = cv2.resize(patch, (64, 64))

    # 1. Raw pixels (flattened)
    features['raw_pixels'] = patch_resized.flatten()

    # 2. HOG features
    features['hog'] = hog(patch_resized, orientations=9, pixels_per_cell=(8, 8),
                        cells_per_block=(2, 2))

    # 3. SIFT features
    sift = cv2.SIFT_create()
    _, des = sift.detectAndCompute(patch_resized, None)
    features['sift'] = des.flatten()[:128] if des is not None else np.zeros(128)

    # 4. LBP features
    features['lbp'] = np.histogram(
        local_binary_pattern(patch_resized, P=8, R=1, method='uniform'),
        bins=10, range=(0, 10))[0]

    # 5. Combined features (normalized)
    features['combined'] = np.histogram(
        np.concatenate([
            features['hog'],
            features['sift'],
            features['lbp']
        ]), bins=50)[0]

    return features