# -*- coding: utf-8 -*-
"""visualize_clusters.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ha2WZzjYme67LtFcx5k9_vMVd50jHvhq
"""

from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

def visualize_clusters(X, clusters, method_name, ft_name, dim_reduction='pca'):
    # Visualize clusters using PCA or t-SNE
    plt.figure(figsize=(12, 8))

    if dim_reduction == 'pca':
        reducer = PCA(n_components=2)
        title = f"PCA - {ft_name} - {method_name}"
    else:
        reducer = TSNE(n_components=2, perplexity=30, random_state=42)
        title = f"t-SNE - {ft_name} - {method_name}"

    X_2d = reducer.fit_transform(X)

    # Create DataFrame for seaborn
    plot_df = pd.DataFrame(X_2d, columns=['x', 'y'])
    plot_df['cluster'] = clusters

    # Plot with seaborn for better visualization
    sns.scatterplot(
        data=plot_df,
        x='x', y='y',
        hue='cluster',
        palette='tab10',
        alpha=0.7,
        s=50
    )
    plt.title(title)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.show()